version: 2
updates:
  - package-ecosystem: "nuget"
    # Files stored in src/Appium.Net directory
    directory: "/src/Appium.Net" 
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
